// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR60iUL8Q3xzZ-bDzgcPrAm6p32hbysrQ',
    appId: '1:1001369232607:web:fd2b0844378a1f5107f56a',
    messagingSenderId: '1001369232607',
    projectId: 'voiceassistant-13319',
    authDomain: 'voiceassistant-13319.firebaseapp.com',
    storageBucket: 'voiceassistant-13319.appspot.com',
    measurementId: 'G-F7D8RCSWMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfAI44zuN_lXWrmK_EmtaaHkIywLP33U',
    appId: '1:1001369232607:android:f4e991667b28d84907f56a',
    messagingSenderId: '1001369232607',
    projectId: 'voiceassistant-13319',
    storageBucket: 'voiceassistant-13319.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRyGBsPG1WTMyUVOJiEDYZay679Afmvq4',
    appId: '1:1001369232607:ios:02738543fef88fbd07f56a',
    messagingSenderId: '1001369232607',
    projectId: 'voiceassistant-13319',
    storageBucket: 'voiceassistant-13319.appspot.com',
    iosBundleId: 'com.rivaan.allen.allen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRyGBsPG1WTMyUVOJiEDYZay679Afmvq4',
    appId: '1:1001369232607:ios:02738543fef88fbd07f56a',
    messagingSenderId: '1001369232607',
    projectId: 'voiceassistant-13319',
    storageBucket: 'voiceassistant-13319.appspot.com',
    iosBundleId: 'com.rivaan.allen.allen',
  );
}
